### ISSUE TITLE
Failed to get the mkv file info

### ISSUE THREAD

**Issue by Fujiwara-Chika** [MkvAutoSubset/MkvAutoSubset#7]
OS Version: macOS 10.14.6 Mojave
MkvToolNix Version: 53.0.0
Fonttools Version: 4.29.1
<img width="840" alt="image" src="https://user-images.githubusercontent.com/44722787/165231290-3110c0b2-068b-4750-82dd-e582dfb38983.png">

**Comment by KurenaiRyu** [comment]
你找一下从哪里知道这个项目的，作者他不愿意在github建号处理，我这边也没法处理。

**Comment by Fujiwara-Chika** [comment]
> 你找一下从哪里知道这个项目的，作者他不愿意在github建号处理，我这边也没法处理。

行吧，那我直接去 VCB 论坛反馈
